config/routes.rb
Rails.application.routes.draw do
  #get "todos",to:"todos#index"
  get "/" => "home#index"
  resources :todos

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum:2 }
  validates :due_date, presence: true
  belongs_to :user

  def due_today?
    due_date == Date.today
  end
  def self.current_user
    all.where(user_id:user.id)
  end
  def self.overdue
    where("due_date < ?", Date.today)
  end
  def self.due_today
    where("due_date = ?", Date.today)
  end
  def self.duelater
    where("due_date > ?", Date.today)
  end
  def self.completed
    all.where(completed: true)
  end
  def self.complete
    all.where(completed: false)
  end
  def self.show_list
    puts "My Todo-List\n\n"
    puts "Overdue\n"
    puts overdue.map { |todo| todo.to_displayable_string }
    puts "\n\n"
    puts "Due Today\n"
    puts due_today.map { |todo| todo.to_displayable_string }
    puts "\n\n"
    puts "Due Later\n"
    puts duelater.map { |todo| todo.to_displayable_string }
  end
  def self.mark_as_complete(todo_id)
    todo = Todo.find(todo_id)
    todo.completed = true
    todo.save
    todo
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :first_name, length: { minimum:2 }
  validates :email, presence: true
  has_secure_password
  has_many :todos
end

app/models/users.rb
class Users < ActiveRecord::Base
  def to_pleasant_string
    "#{id} #{user_name} #{email_id} #{password}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action:ensure_user_logged_in
  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action:ensure_user_logged_in
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id]=user.id
      redirect_to "/"
    else
      flash[:error]= "Your login attempt was invalid. please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.find(id)
    render "todos"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date].to_s
    puts due_date
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id:current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action:ensure_user_logged_in
  def new
    #@todos = Todo.of_user(current_user)
    render "users/new"
  end
  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password]
    )
      if new_user.save
        session[:current_user_id] = new_user.id
        redirect_to "/"
      else
        flash[:error] = new_user.errors.full_messages.join(", ")
        redirect_to "/users/new"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class= "Home-title"> Welcome to Todo Homepage </h1>

<h3 class="Home-authenticate">
  if you are a new user, <%= link_to :"sign up here", new_user_path %>
</h3>

<h3 class="Home-authenticate">
  if you are an existing user, <%= link_to :"sign-in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Todo Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
       Welcome <%= @current_user.first_name %>!
       <%= link_to "Sign-out", destroy_session_path, method:"delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-title"> <%= section_title%> </p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count%> / <%= todos.count %>  </p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">

          <%= form_with(url: "/todos/#{todo.id}",method:"put" ) do %>
            <%= check_box_tag "completed", value=nil, checked = todo.completed, :onclick=>"this.form.submit()" %>
          <% end %>

          <% if todo.completed %>
            <p style="text-decoration: line-through;"> <%= todo.todo_text %> </p>
          <% else %>
            <%= todo.todo_text %>
          <% end %>

          <% if show_due_date %>
            <p class="TodoItem-dueDate"> <%=todo.due_date.to_s(:short)%> </p>
          <% end %>

          <a class="TodoItem-delete" href="javascript:void(0)">
            <%= form_with(url: "/todos/#{todo.id}", method:"delete") do %>
              <%= image_submit_tag("trashcan.png") %>
            <% end %>
          </a>
        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPgeMain">
  <article>
    <h1 class="TodoPage-title"> My Todo-List</h1>

    <%= form_with(url: "/todos",method:"post",class: "AddTodo") do %>
      <%= text_field_tag 'todo_text', nil, placeholder:"what is next?", class:"AddTodo-text" %>
      <%= date_field :due_date, :"" , class:"AddTodo-date" %>
      <%= submit_tag 'Add', class:"AddTodo-button" %>
    <% end %>

    <%= render partial:"todo-section", locals: {
      section_title: "Overdue",
      todos: @todos.overdue.complete,
      show_due_date:true
    } %>

    <%= render partial:"todo-section", locals: {
      section_title: "Due Today",
      todos: @todos.due_today,
      show_due_date:false
    } %>

    <%= render partial:"todo-section", locals: {
      section_title: "Due Later",
      todos: @todos.duelater,
      show_due_date:true
    } %>

  </article>
</main>

app/views/todos/todos.html.erb
<p> This shows a single reocrd </p>

app/views/users/new.html.erb
<p class=NewUsers-title > Welcome to new user!</p>

<section class="UsersNew">
<%= form_with url: users_path do |form| %>
  <div class ="Form-section">
    <p class ="FormInput-label"> First Name: </p>
      <input  class = "Form-input" type="text" id="text_field" name="first_name" autofocus >
  </div>
  <div class ="Form-section">
    <p class ="FormInput-label">
      Last Name:
    </p>
      <%= form.text_field :last_name,
        class: "Form-input"
      %>
  </div>

  <div class = "Form-section">
    <p class ="FormInput-label"> Email: </p>
      <%= form.email_field :email,class: "Form-input" %>
  </div>

  <div class = "Form-section">
    <p class ="FormInput-label"> Password: </p>
      <%= form.password_field :password,class: "Form-input" %>
  </div>

  <div class= "Form-section">
    <%= form.submit "Sign-Up!", class:"Form-submit" %>
  </div>
    <% end %>
</section>